version: 0.0.2
apiVersion: v2
appVersion: "1.16.0"
name: tea-plantation
type: application
description: A Helm chart for tea plantation app that represented by several services

dependencies:
  - name: discovery
    version: 0.0.1
    repository: "file://../discovery"
  - name: gateway
    version: 0.0.1
    repository: "file://../gateway"
  - name: inventory
    version: 0.0.1
    repository: "file://../inventory"
  - name: plantation
    version: 0.0.1
    repository: "file://../plantation"