### Parent chart for plantation services
global:
  discovery:
    port: 8761
    serviceName: discovery-eureka-service
  postgres:
    port: 5432
    host: postgres-postgresql.postgres.svc.cluster.local
  rabbitmq:
    port: 5672
    host: rabbitmq.rabbitmq.svc.cluster.local
#    add inventory service, before it containers to wait for psql and rabbitmq

gateway:
  tracing:
    enabled: false
inventory:
  tracing:
    enabled: false
