spring:
  application:
    name: order-service
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost:30002}/tea?currentSchema=order-service
    username: order-user
    password: ord!@#
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:31691}
    username: rabbitmq
    password: rab!@#
eureka:
  instance:
    prefer-ip-address: true # for k8s correct work
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  tracing:
    enabled: ${TRACING_ENABLED:false}
    sampling:
      probability: 1.0

server:
  port: ${SERVER_PORT:8081}

tea:
  plantation:
    name: 'plantation-service'
    host: 'http://localhost:8080'
    endpoint: '/v1/tea/uuid/{teaUuid}'

logging:
  level:
    root: info
    com:
      tea:
        order: debug
    org:
      hibernate:
        SQL: debug
