spring:
  application:
    name: order-service
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:30002/tea?currentSchema=order-service
    username: order-user
    password: ord!@#
  rabbitmq:
    host: localhost
    port: 31691
    username: rabbitmq
    password: rab!@#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8081

tea:
  plantation:
    name: 'plantation-service'
    host: 'http://localhost:8080'
    endpoint: '/v1/tea/uuid/{teaUuid}'

logging:
  level:
    root: info
    com:
      tea:
        order: debug
    org:
      hibernate:
        SQL: debug
