spring:
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:30002/tea?currentSchema=order-service
    username: order-user
    password: ord!@#

server:
  port: 8081

tea:
  plantation:
    host: 'http://localhost:8080'
    endpoint: '/v1/tea/uuid/{teaUuid}'

logging:
  level:
    root: info
    com:
      tea:
        order: debug
    org:
      hibernate:
        SQL: debug
