spring:
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:30002/tea?currentSchema=order-service
    username: order-user
    password: ord!@#

server:
  port: 8081

logging:
  level:
    root: info
