server:
  port: 9090
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: plantation-service
          uri: http://localhost:8080
          predicates:
            - Path=/v1/tea/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/inventory/**
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/v1/order/**