server:
  port: ${SERVER_PORT:9090}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: false
    should-unregister-on-shutdown: false
management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: 1.0
spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: plantation-service
          uri: lb://plantation-service
          predicates:
            - Path=/v1/tea/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/v1/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/order/**