spring:
  application:
    name: inventory-service
  jpa:
    open-in-view: off
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost:30002}/tea?currentSchema=inventory-service
    username: inventory-user
    password: inv!@#
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:31691}
    username: rabbitmq
    password: rab!@#
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: 1.0

server:
  port: ${SERVER_PORT:8082}

logging:
  level:
    root: info
    com:
      tea:
        inventory: debug
