apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  # It works only with the LoadBalancer type
  type: LoadBalancer
  ports:
    - port: 80
      name: api
      targetPort: web
    - port: 8080
      name: ui
      targetPort: dashboard
  selector:
    app: traefik
