package com.tea.order.domain;

public enum OrderStatus {
    NEW,
    VALIDATING, VALIDATED, VALIDATION_ERROR,
    ALLOCATING, ALLOCATED, ALLOCATION_ERROR, PENDING_INVENTORY,
    PICKED_UP, CANCELED
}
