apiVersion: v1
kind: Service
metadata:
  name: {{ include "plantation.fullname" . }}
  labels:
    {{- include "plantation.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plantation.selectorLabels" . | nindent 4 }}
