package com.tea.order.sm;

public enum OrderEvent {
    VALIDATE, VALIDATION_OK, VALIDATION_FAILED,
    ALLOCATE, ALLOCATION_OK, ALLOCATION_FAILED, WAIT_FOR_INVENTORY,
    DELIVER, DELIVERY_OK, DELIVERY_FAILED,
    ORDER_PICK_UP
}
