spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:30001/tea-plantation?authSource=admin
      database: tea-plantation
      uuid-representation: standard
      replica-set-name: rs0
  rabbitmq:
    host: localhost
    port: 31691
    username: rabbitmq
    password: rab!@#

mongock:
  mongo-db:
    read-concern: local
  transactionEnabled: true
  migration-scan-package: com.tea.plantation.migration

tea:
  plantation:
    synchronize-with-inventory-duration: PT1M
  inventory:
    host: 'http://localhost:8082'
    endpoint: '/v1/inventory/tea/{teaId}'

logging:
  level:
    root: info
    com:
      tea:
        plantation: debug
      mongodb: debug
    org:
      springframework:
        data:
          mongodb: debug
      apache:
        hc:
          client5:
            http: info
    io:
      mongock: debug