spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:30001/tea-plantation?authSource=admin
      database: tea-plantation
mongock:
  transactionEnabled: false
  migration-scan-package: com.tea.plantation.migration

logging:
  level:
    root: debug
