spring:
  application:
    name: plantation-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:30001/tea-plantation?authSource=admin
      database: tea-plantation
      uuid-representation: standard
      replica-set-name: rs0
  rabbitmq:
    host: localhost
    port: 31691
    username: rabbitmq
    password: rab!@#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0

mongock:
  mongo-db:
    read-concern: local
  transactionEnabled: true
  migration-scan-package: com.tea.plantation.migration

tea:
  plantation:
    synchronize-initial-delay: PT1M
    synchronize-with-inventory-duration: PT1M
  inventory:
    name: 'inventory-service'
    host: 'http://localhost:8082'
    endpoint: '/v1/inventory/tea/{teaId}'

logging:
  level:
    root: info
    com:
      mongodb: info
      tea:
        plantation: debug
    org:
      springframework:
        data:
          mongodb: info
      apache:
        hc:
          client5:
            http: info
    io:
      mongock: info