spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:30001/tea-plantation?authSource=admin
      database: tea-plantation
      uuid-representation: standard
mongock:
  transactionEnabled: false
  migration-scan-package: com.tea.plantation.migration

tea:
  inventory:
    host: 'http://localhost:8082'
    endpoint: '/v1/inventory/tea/{teaId}'

logging:
  level:
    root: info
