apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-cluster" (include "discovery.fullname" .) }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}
