{{- if .Values.service.createNodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-node" (include "discovery.fullname" .) }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.global.discovery.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}
{{- end }}
