apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.discovery.serviceName }}
  labels:
    {{- include "discovery.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.global.discovery.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "discovery.selectorLabels" . | nindent 4 }}
